version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r html/* $READTHEDOCS_OUTPUT/html/
    - ls -hl $READTHEDOCS_OUTPUT
    - ls -hl $READTHEDOCS_OUTPUT/html/ | grep index
