var annotated_dup =
[
    [ "GL", "dd/d9a/namespaceGL.html", [
      [ "VertexArrayObject", "d9/d82/structGL_1_1VertexArrayObject.html", "d9/d82/structGL_1_1VertexArrayObject" ],
      [ "ArrayBuffer", "d6/dba/structGL_1_1ArrayBuffer.html", "d6/dba/structGL_1_1ArrayBuffer" ],
      [ "ElementArrayBuffer", "da/dd6/structGL_1_1ElementArrayBuffer.html", "da/dd6/structGL_1_1ElementArrayBuffer" ],
      [ "DrawableMesh", "d7/d5e/structGL_1_1DrawableMesh.html", "d7/d5e/structGL_1_1DrawableMesh" ],
      [ "DrawableLineSet", "d9/d38/structGL_1_1DrawableLineSet.html", "d9/d38/structGL_1_1DrawableLineSet" ]
    ] ],
    [ "std", null, [
      [ "formatter&lt; Eigen::Matrix&lt; Scalar, n_dim, 1 &gt; &gt;", "de/dfd/structstd_1_1formatter_3_01Eigen_1_1Matrix_3_01Scalar_00_01n__dim_00_011_01_4_01_4.html", null ],
      [ "formatter&lt; Eigen::Matrix&lt; Scalar, n_dim, n_dim, 0, n_dim, n_dim &gt; &gt;", "d4/d41/structstd_1_1formatter_3_01Eigen_1_1Matrix_3_01Scalar_00_01n__dim_00_01n__dim_00_010_00_01n__dim_00_01n__dim_01_4_01_4.html", null ]
    ] ],
    [ "UI", null, [
      [ "Menubar", "d6/de2/classUI_1_1Menubar.html", "d6/de2/classUI_1_1Menubar" ],
      [ "Toolbar", "d1/d84/classUI_1_1Toolbar.html", "d1/d84/classUI_1_1Toolbar" ]
    ] ],
    [ "AABB", "d2/d1a/classAABB.html", "d2/d1a/classAABB" ],
    [ "AABBSet", "d7/d83/structAABBSet.html", "d7/d83/structAABBSet" ],
    [ "ArrowSet", "d6/d5f/structArrowSet.html", "d6/d5f/structArrowSet" ],
    [ "BVH", "de/de9/classBVH.html", "de/de9/classBVH" ],
    [ "BVHNode", "d4/d59/structBVHNode.html", null ],
    [ "Camera", "d7/d7e/structCamera.html", "d7/d7e/structCamera" ],
    [ "Context", "d6/d7a/structContext.html", null ],
    [ "Controller", "d9/d85/classController.html", "d9/d85/classController" ],
    [ "DebugOptions", "d3/dd6/structDebugOptions.html", "d3/dd6/structDebugOptions" ],
    [ "Edge", "d2/d4f/structEdge.html", "d2/d4f/structEdge" ],
    [ "Face", "d0/d02/structFace.html", "d0/d02/structFace" ],
    [ "FragmentProcessor", "d6/d3d/classFragmentProcessor.html", "d6/d3d/classFragmentProcessor" ],
    [ "FragmentShaderPayload", "db/dd4/structFragmentShaderPayload.html", "db/dd4/structFragmentShaderPayload" ],
    [ "FrameBuffer", "dc/d5b/classFrameBuffer.html", "dc/d5b/classFrameBuffer" ],
    [ "Group", "d0/db7/classGroup.html", "d0/db7/classGroup" ],
    [ "Halfedge", "df/d02/structHalfedge.html", "df/d02/structHalfedge" ],
    [ "HalfedgeMesh", "dc/d6d/classHalfedgeMesh.html", "dc/d6d/classHalfedgeMesh" ],
    [ "Intersection", "d6/d30/structIntersection.html", "d6/d30/structIntersection" ],
    [ "KineticState", "d1/d96/structKineticState.html", null ],
    [ "Light", "d5/d79/structLight.html", "d5/d79/structLight" ],
    [ "LineSet", "d5/d11/structLineSet.html", "d5/d11/structLineSet" ],
    [ "LinkedList", "d7/dde/classLinkedList.html", "d7/dde/classLinkedList" ],
    [ "LinkedListNode", "d6/d73/structLinkedListNode.html", null ],
    [ "Material", "d2/d10/structMaterial.html", "d2/d10/structMaterial" ],
    [ "Mesh", "da/d29/structMesh.html", "da/d29/structMesh" ],
    [ "Object", "d8/d4b/classObject.html", "d8/d4b/classObject" ],
    [ "overloaded", "d9/d94/structoverloaded.html", null ],
    [ "PhongMaterial", "dc/df1/structPhongMaterial.html", "dc/df1/structPhongMaterial" ],
    [ "Platform", "df/d1e/classPlatform.html", "df/d1e/classPlatform" ],
    [ "PreviewRenderer", "d0/dd8/classPreviewRenderer.html", "d0/dd8/classPreviewRenderer" ],
    [ "Rasterizer", "d3/d7a/classRasterizer.html", "d3/d7a/classRasterizer" ],
    [ "RasterizerRenderer", "d7/db0/classRasterizerRenderer.html", "d7/db0/classRasterizerRenderer" ],
    [ "Ray", "dd/d5e/structRay.html", null ],
    [ "RenderEngine", "d3/d2f/classRenderEngine.html", "d3/d2f/classRenderEngine" ],
    [ "Scene", "d5/d9c/classScene.html", "d5/d9c/classScene" ],
    [ "Shader", "d9/d69/classShader.html", "d9/d69/classShader" ],
    [ "SortNode", "d9/d4d/structSortNode.html", null ],
    [ "SpinLock", "dd/d57/classSpinLock.html", "dd/d57/classSpinLock" ],
    [ "Triangle", "d2/d51/classTriangle.html", "d2/d51/classTriangle" ],
    [ "Uniforms", "de/d97/structUniforms.html", null ],
    [ "Vertex", "df/dd0/structVertex.html", "df/dd0/structVertex" ],
    [ "VertexProcessor", "d1/d19/classVertexProcessor.html", "d1/d19/classVertexProcessor" ],
    [ "VertexShaderPayload", "d9/d78/structVertexShaderPayload.html", "d9/d78/structVertexShaderPayload" ],
    [ "WhittedRenderer", "da/db7/classWhittedRenderer.html", "da/db7/classWhittedRenderer" ]
];